name: play
description: a library dart simple for play audio or video any format on cross platform.
version: 0.0.17
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/play
issue_tracker: https://github.com/azkadev/play/issues

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^3.0.1
  dart_vlc: ^0.4.0
  universal_io: ^2.0.4
  video_player: ^2.5.1

# flutter:
#   assets:
#     - assets/video/azkadev.mp4