name: play
description: a library dart simple for play audio or video any format on cross platform.
version: 0.0.13
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/play
issue_tracker: https://github.com/azkadev/play/issues

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^1.1.1
  dart_vlc: ^0.3.0
  universal_io: ^2.0.4
  video_player: ^2.4.8

flutter:
  assets:
    - assets/video/azkadev.mp4