name: play
description: a library dart simple for play audio or video any format on cross platform.
version: 0.0.38
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/play
issue_tracker: https://github.com/azkadev/play/issues

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
  

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  galaxeus_lib: ^0.0.92
  googleapis_client: ^0.0.6
  path: ^1.8.3
  media_kit: ^1.1.7                              # Primary package.
  media_kit_video: ^1.1.8                        # For video rendering.
  media_kit_libs_video: ^1.0.1                   # Native video dependencies.
 
executables:
  play_cli: play
  play: play
