name: play
description: a library dart simple for play audio or video any format on cross platform.
version: 0.0.24
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/play
issue_tracker: https://github.com/azkadev/play/issues

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
  
environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  video_player: ^2.5.1 
  media_kit: ^0.0.1
  media_kit_video: ^0.0.1
  galaxeus_lib: ^0.0.56
  media_kit_libs_windows_video: ^1.0.0
  media_kit_libs_windows_audio: ^1.0.1


executables:
  play_cli: play
  play: play